version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: creato-postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: creato
      POSTGRES_PASSWORD: creato123
      POSTGRES_DB: creato_dev
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
